### ISSUE TITLE
缺少 libcurl.dll

### ISSUE THREAD

**Issue by lideming** [LER0ever/Israfil-builds#1]

**Comment by LER0ever** [comment]
额，小意外，好像编译脚本是没有复制curl到目标目录，我明天下午加一下。
顺便说一下，这个项目还在早期开发，现在除了test-qqmusic可以搜点歌以外没什么用

**Comment by LER0ever** [comment]
现在libcurl.dll加到artifacts里了，Windows下什么都不装应该都可以运行了。
（还有issue推荐到主项目LER0ever/Israfil提交，谢谢）
